name: Mirror Repository

on:
  push:
    branches:
      - main  # Trigger this workflow on push to 'main' branch (adjust as needed)

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v2
      with:
        repository: kRxZykRxZy/Image-Hoster
        token: ${{ secrets.GITHUB_TOKEN }}
        path: source-repo

    - name: Set up Git for Mirroring
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Mirror to Destination Repository
      run: |
        cd source-repo
        git remote set-url --add --push origin https://github.com/UBBload/Mirror.git
        git push --mirror
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up
      run: rm -rf source-repo
